# Ai4Arctic/model/Makefile

# Устанавливает цель по умолчанию
.DEFAULT_GOAL := help

.PHONY: help go-backend

# Показывает список доступных команд
help:
	@echo "Ai4Arctic project"
	@echo "Usage:"
	@echo "  make go-backend - ..."

go-backend:
    python -m grpc_client.client
