# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'geo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgeo.proto\x12\x03geo\"\x91\x01\n\x05Layer\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\t\x12\x15\n\x08magt_min\x18\x04 \x01(\x01H\x00\x88\x01\x01\x12\x15\n\x08magt_max\x18\x05 \x01(\x01H\x01\x88\x01\x01\x12\x10\n\x08geometry\x18\x06 \x01(\tB\x0b\n\t_magt_minB\x0b\n\t_magt_max\"Z\n\x18ImportMagtDatasetRequest\x12\x14\n\x0c\x64\x61taset_name\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x12\x1a\n\x06layers\x18\x03 \x03(\x0b\x32\n.geo.Layer\"Q\n\x19ImportMagtDatasetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\ndataset_id\x18\x02 \x01(\x03\x12\x0f\n\x07message\x18\x03 \x01(\t2f\n\x10GeoImportService\x12R\n\x11ImportMagtDataset\x12\x1d.geo.ImportMagtDatasetRequest\x1a\x1e.geo.ImportMagtDatasetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAYER']._serialized_start=19
  _globals['_LAYER']._serialized_end=164
  _globals['_IMPORTMAGTDATASETREQUEST']._serialized_start=166
  _globals['_IMPORTMAGTDATASETREQUEST']._serialized_end=256
  _globals['_IMPORTMAGTDATASETRESPONSE']._serialized_start=258
  _globals['_IMPORTMAGTDATASETRESPONSE']._serialized_end=339
  _globals['_GEOIMPORTSERVICE']._serialized_start=341
  _globals['_GEOIMPORTSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
