"""1.0_updating_users_table

Revision ID: 108895874c39
Revises: 5b23dc847679
Create Date: 2026-05-08 00:14:08.705185

"""

from typing import Sequence, Union  # noqa

from alembic import op  # noqa
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision: str = "108895874c39"
down_revision: Union[str, Sequence[str], None] = "5b23dc847679"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
