"""add MagtFeature

Revision ID: 4186c4dfddbc
Revises: 73af3d064a51
Create Date: 2026-06-16 10:05:49.581588

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4186c4dfddbc"
down_revision: Union[str, Sequence[str], None] = "73af3d064a51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "magt_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=False),
        sa.Column("magt_min", sa.Float(), nullable=False),
        sa.Column("magt_max", sa.Float(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("idx_ndvi_geom"), table_name="ndvi", postgresql_using="gist")
    op.drop_table("ndvi")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ndvi",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=75), autoincrement=False, nullable=False),
        sa.Column("year", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "ndvi",
            sa.NUMERIC(precision=7, scale=6),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ndwi_1",
            sa.NUMERIC(precision=7, scale=6),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ndwi_2",
            sa.NUMERIC(precision=7, scale=6),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "savi",
            sa.NUMERIC(precision=7, scale=6),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ndvi_pkey")),
    )
    op.create_index(
        op.f("idx_ndvi_geom"), "ndvi", ["geom"], unique=False, postgresql_using="gist"
    )
    op.drop_table("magt_features")
    # ### end Alembic commands ###
