"""add email for users

Revision ID: 73af3d064a51
Revises: 108895874c39
Create Date: 2026-05-13 13:07:37.797048

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "73af3d064a51"
down_revision: Union[str, Sequence[str], None] = "108895874c39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", postgresql.CITEXT(), nullable=True))
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=75),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.alter_column(
        "users",
        "name",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=75),
        existing_nullable=False,
    )
    op.drop_column("users", "email")
    # ### end Alembic commands ###
