"""add users and ndvi

Revision ID: cddf712fd47d
Revises:
Create Date: 2026-05-02 22:14:10.279192

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cddf712fd47d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ndvi",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=75), nullable=False),
        sa.Column("year", sa.Date(), nullable=False),
        sa.Column("ndvi", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("ndwi_1", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("ndwi_2", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("savi", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index(
    #    "idx_ndvi_geom", "ndvi", ["geom"], unique=False, postgresql_using="gist"
    # )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=75), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_table("users")
    # op.drop_index("idx_ndvi_geom", table_name="ndvi", postgresql_using="gist")
    op.drop_table("ndvi")
    # ### end Alembic commands ###
