# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "geo.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tgeo.proto\x12\x03geo"+\n\x18ImportMagtDatasetRequest\x12\x0f\n\x07geojson\x18\x01 \x01(\t"=\n\x19ImportMagtDatasetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2f\n\x10GeoImportService\x12R\n\x11ImportMagtDataset\x12\x1d.geo.ImportMagtDatasetRequest\x1a\x1e.geo.ImportMagtDatasetResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "geo_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_IMPORTMAGTDATASETREQUEST"]._serialized_start = 18
    _globals["_IMPORTMAGTDATASETREQUEST"]._serialized_end = 61
    _globals["_IMPORTMAGTDATASETRESPONSE"]._serialized_start = 63
    _globals["_IMPORTMAGTDATASETRESPONSE"]._serialized_end = 124
    _globals["_GEOIMPORTSERVICE"]._serialized_start = 126
    _globals["_GEOIMPORTSERVICE"]._serialized_end = 228
# @@protoc_insertion_point(module_scope)
